# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/afernandez-atsistemas/repo-specs-cocoapods.git'


target 'Firebase Showcase' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Firebase Showcase
  pod 'Alamofire'
  pod 'LanguageManager-iOS'
  pod 'PromiseKit'
  pod 'ObjectMapper'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/DynamicLinks'
  pod 'TestingPrivatePod'

end
